[features]
seeds = false
skip-lint = false
[programs.localnet]
decentralized_invoices = "JCjA4ujSA9usvV2HJUZaUDaBwNNK1dCHhjaBwDYP1rPs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/ixmorrow/.config/solana/test-wallet3.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
